#!/bin/bash

# Example script
echo "This file was generated by the Python server. As a demonstration for script execution on server initiated by client." > ./server_output.txt 

# Your script here
ping google.com -c 2 >> ./server_ouput.txt
