#!/bin/bash

<<<<<<< HEAD
# Example script
echo "This file was generated by the Python server. As a demonstration for script execution on server initiated by client." > ./server_output.txt 

# Your script here
ping google.com -c 2 >> ./server_ouput.txt
=======
# Example
echo "This seems to be working" > /path/to/file/example.txt

# Your server script here
>>>>>>> d4bbdc181da2f2aa19056dba42d5748d589df08d
